when@dev: &dev
  zenstruck_foundry:
    global_state:
      - App\Tests\Story\UserStory
      - App\Tests\Story\PostStory
      - App\Tests\Story\CommentStory
    make_story:
      default_namespace: 'App\Tests\Story'
    make_factory:
      default_namespace: 'App\Tests\Factory'

when@test: *dev
